### PR TITLE
Fix dependencies remove automerge

### PR DESCRIPTION
**Pull request by xylar**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by xylar** [comment]
Unfortunately, incorrect dependencies in #9 are causing https://github.com/conda-forge/google-cloud-aiplatform-feedstock/pull/11 to fail its `pip check`:
```
pip check
grpcio-status 1.48.0 has requirement grpcio>=1.48.0, but you have grpcio 1.46.3.
```
Since dependencies change here with (nearly) every release, this is not a feedstock that can safely have the bot automerge feature turned on.  I am happy to maintain it if it's too much trouble to keep track of the dependency changes from release to release.

**Comment by xylar** [comment]
@conda-forge-admin, please rerender

**Comment by xylar** [comment]
@hadim and @sugatoray, this is ready to merge.  Let me know if you have concerns about me removing the automerge or adding myself as a maintainer.

**Comment by sugatoray** [comment]
@xylar Thank you, for the PR. I also saw the grpcio-status version error somewhere else. I believe it will be nice to have you as a co-maintainer. 

About auto-merge, if things are changing very often, yes I can see why it could be a problem. 

I will go ahead and merge the PR now.

**Comment by xylar** [comment]
@sugatoray, thanks for merging!

> About auto-merge, if things are changing very often, yes I can see why it could be a problem.

In my experience, the bot `automerge` is only safe for feedstocks where the dependencies *never* change from one release to the next.  It is usually a lot more work to fix incorrect dependencies after the fact than to manually update them correctly in the first place.  Hopefully in the longer run, conda-forge will have a better way of detecting dependency changes and suggesting them as part of bot PRs but were not there yet.

**Pull request merged**
